#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("BluetoothChat.Resource", IsApplication=true)]

namespace BluetoothChat
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070006
			public const int button_scan = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int button_send = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int discoverable = 2131165195;
			
			// aapt resource value: 0x7f070008
			public const int edit_text_out = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int @in = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int new_devices = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int paired_devices = 2131165187;
			
			// aapt resource value: 0x7f07000a
			public const int scan = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int title_left_text = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int title_new_devices = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int title_paired_devices = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int title_right_text = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int custom_title = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int device_list = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int device_name = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int message = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int option_menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int bt_not_enabled_leaving = 2130968579;
			
			// aapt resource value: 0x7f04000d
			public const int button_scan = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int connect = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int discoverable = 2130968591;
			
			// aapt resource value: 0x7f04000a
			public const int none_found = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int none_paired = 2130968585;
			
			// aapt resource value: 0x7f040002
			public const int not_connected = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int scanning = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int select_device = 2130968584;
			
			// aapt resource value: 0x7f040001
			public const int send = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int title_connected_to = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int title_connecting = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int title_not_connected = 2130968582;
			
			// aapt resource value: 0x7f04000c
			public const int title_other_devices = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int title_paired_devices = 2130968587;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
